// ============================================================
//  cases.js — Banco de casos do Conduta.
//  Para adicionar um novo caso: copie o bloco abaixo e cole
//  antes do "];" final do array CASES.
//
//  Estrutura de cada caso:
//  {
//    diagnosis: "Nome do diagnóstico",
//    aliases: ["variação 1", "variação 2"],  // termos aceitos como resposta
//    cid: "X00",
//    category: "Especialidade",
//    clues: [
//      "Pista 1 — vaga (queixa/idade/sexo)",
//      "Pista 2 — evolução dos sintomas",
//      "Pista 3 — história prévia / exposição",
//      "Pista 4 — imagem e labs",
//      "Pista 5 — exame confirmatório (mata-mata)"
//    ],
//    clue_labels: ["Label1","Label2","Label3","Label4","Label5"],
//    explanation: "Discussão clínica resumida.",
//    reference: "Referência bibliográfica.",
//    difficulty: 1  // 1=Fácil, 2=Médio, 3=Difícil
//  }
// ============================================================

const CASES = [
  {id:1,diagnosis:"Dengue",aliases:["dengue clássica","febre do dengue","dengue com sinais de alarme"],cid:"A90",category:"Infectologia",
  clues:[
    "Mulher, 28 anos, previamente hígida, procura UBS referindo febre há 3 dias, cansaço intenso e dor de cabeça que piora ao movimentar os olhos. Não consegue trabalhar.",
    "A febre atinge 39,5°C com pouca resposta a antitérmicos. Surgem dores musculares intensas e articulares difusas. Sem tosse, sem coriza, sem sintomas urinários.",
    "Mora em Campinas-SP. Vizinhos com quadro semelhante nas últimas 2 semanas. Município em alerta epidemiológico. Não viajou recentemente. Sem histórico de doença prévia relevante.",
    "Hemograma: leucócitos 3.200/mm³, plaquetas 98.000/mm³, hematócrito 38%. Exame físico revela rubor facial e exantema maculopapular em tronco. Prova do laço: positiva.",
    "NS1 Ag positivo no 3º dia de doença. IgM anti-dengue reagente. PCR confirma sorotipo DENV-3 em circulação no município."
  ],
  clue_labels:["Apresentação inespecífica","Evolução dos sintomas","História epidemiológica","Exame físico e hemograma","Confirmação sorológica"],
  explanation:"Dengue é arbovirose transmitida pelo Aedes aegypti. O quadro inicial é inespecífico — febre, mialgia e cefaleia — o que dificulta o diagnóstico precoce. A dor retro-orbital e o exantema aparecem depois. Leucopenia e trombocitopenia são marcadores laboratoriais característicos. A classificação de risco do MS orienta o manejo. Tratamento sintomático.",
  reference:"Ministério da Saúde. Dengue: diagnóstico e manejo clínico. 5ª ed. 2016. PAHO/WHO Guidelines 2009.",difficulty:1},

  {id:2,diagnosis:"Leptospirose",aliases:["doença de weil","febre dos arrozais"],cid:"A27",category:"Infectologia",
  clues:[
    "Homem, 34 anos, atendido no PS com febre, cefaleia intensa e mialgia há 5 dias, com piora progressiva. Está prostrado e mal consegue caminhar.",
    "No 6º dia surgem icterícia leve e oligúria. Dor lombar bilateral. Paciente refere que a urina ficou escura. Febre persiste em 39,8°C.",
    "Trabalha como gari em São Paulo. Há 8 dias, atuou na remoção de entulho após enchente, com contato direto com água de inundação por horas. Sem uso de EPI.",
    "Creatinina 2,8 → 4,1 mg/dL em 24h. Bilirrubina total 4,2 mg/dL (direta). CPK 2.400 U/L. Plaquetas 68.000/mm³. Urina: cilindros granulosos, piúria. Rx tórax: infiltrado bilateral.",
    "MAT (microaglutinação) reagente 1:400 para sorogrupo Icterohaemorrhagiae. Sufusão hemorrágica conjuntival ao exame — achado patognomônico. Hemocultura positiva em fase aguda."
  ],
  clue_labels:["Síndrome febril inespecífica","Evolução com disfunção orgânica","Exposição ocupacional","Imagem e laboratório","Sorologia confirmatória"],
  explanation:"Leptospirose é zoonose endêmica no Brasil, especialmente em períodos chuvosos. A forma grave (Síndrome de Weil) cursa com insuficiência renal, icterícia e diátese hemorrágica. A sufusão conjuntival é achado patognomônico. Diagnóstico confirmado pela MAT. Tratamento: penicilina cristalina (grave) ou doxiciclina (leve).",
  reference:"MS Brasil. Guia de Vigilância em Saúde: Leptospirose, 2017. Bharti AR et al. Lancet Infect Dis 2003.",difficulty:2},

  {id:3,diagnosis:"Doença de Chagas",aliases:["tripanossomíase americana","chagas agudo","chagas"],cid:"B57",category:"Infectologia",
  clues:[
    "Criança, 6 anos, levada à UBS por febre persistente há 15 dias, cansaço fácil e inchaço ao redor do olho esquerdo. Mãe acha que foi picada de inseto.",
    "O edema palpebral esquerdo é indolor, não pruriginoso, sem sinais de celulite. A febre é vespertina e irregular. A criança está cada vez mais prostrada.",
    "Família mora no interior da Bahia, em casa de adobe. Há 3 semanas encontraram um inseto grande e achatado (barbeiro) no quarto. Sem histórico de doença prévia.",
    "Ao exame: hepatoesplenomegalia, adenopatia generalizada, ECG com bloqueio de ramo direito de 1º grau. Esfregaço de sangue periférico: formas tripomastigotas visualizadas.",
    "Sorologia: IgG e IgM por imunofluorescência indireta e ELISA ambos reagentes para Trypanosoma cruzi. Xenodiagnóstico positivo."
  ],
  clue_labels:["Febre e edema palpebral","Caracterização do edema","Histórico e exposição vetorial","Exame físico e parasitoscopia","Sorologia confirmatória"],
  explanation:"Doença de Chagas aguda tem como marca o sinal de Romaña (edema bipalpebral unilateral indolor) quando a porta de entrada é conjuntival. É doença de notificação compulsória. O diagnóstico agudo é feito pelo encontro do parasita no sangue. Tratamento com benznidazol indicado na fase aguda.",
  reference:"Rassi A Jr et al. Chagas disease. Lancet 2010. MS Brasil - Consensus on Chagas Disease. Rev Soc Bras Med Trop 2020.",difficulty:2},

  {id:4,diagnosis:"Tuberculose Pulmonar",aliases:["tuberculose","tb pulmonar","tb"],cid:"A15",category:"Pneumologia / Infectologia",
  clues:[
    "Homem, 42 anos, procura UBS com tosse há 3 semanas. Refere que a tosse começou seca e agora é produtiva. Está muito cansado e sem apetite.",
    "Perde peso sem fazer dieta — emagreceu 7 kg em 2 meses. Tosse noturna com sudorese que molha o lençol. Expectoração com estrias avermelhadas esporadicamente.",
    "Etilista, mora em albergue no centro de São Paulo com 40 pessoas. Contato com colega de quarto que teve diagnóstico de TB há 4 meses e foi transferido para hospital.",
    "Radiografia de tórax: infiltrado em lobo superior direito com área de cavitação. Adenopatia hilar discreta. PPD = 18 mm. BAAR em escarro: 2+ em 2 de 3 amostras.",
    "Cultura em Löwenstein-Jensen: crescimento de Mycobacterium tuberculosis. Teste de sensibilidade: sensível a rifampicina, isoniazida, pirazinamida e etambutol."
  ],
  clue_labels:["Tosse inespecífica","Síndrome consuntiva","Histórico e contato","Imagem e baciloscopia","Cultura confirmatória"],
  explanation:"Tuberculose pulmonar é a forma mais comum (85% dos casos). A tríade tosse > 3 semanas + sudorese noturna + emagrecimento deve sempre levantar suspeita. Cavitação em lobo superior é clássica. O diagnóstico definitivo é pela cultura. Tratamento: RHZE por 2 meses, depois RH por 4 meses. Notificação compulsória.",
  reference:"MS Brasil - Manual de Recomendações para o Controle da Tuberculose, 2019. WHO Treatment Guidelines 2022.",difficulty:1},

  {id:5,diagnosis:"Infarto Agudo do Miocárdio com Supra de ST",aliases:["iamcsst","iam com supra","infarto","iamcst"],cid:"I21",category:"Cardiologia",
  clues:[
    "Homem, 58 anos, acorda às 3h com desconforto no peito descrito como 'peso' e 'aperto'. Tomou omeprazol achando que era azia, mas a dor não passou.",
    "Após 40 minutos a dor irradia para o braço esquerdo e mandíbula. Surge sudorese fria, palidez e náusea intensa. Chama o SAMU.",
    "Hipertenso há 10 anos, diabético tipo 2, tabagista (30 maços-ano). Pai faleceu de infarto aos 55 anos. PA: 145/92 mmHg. FC: 102 bpm. SatO₂: 94%.",
    "ECG imediato: supradesnivelamento de ST ≥ 2mm em V1–V4, com imagem em espelho em derivações inferiores. Bloqueio de ramo esquerdo novo. Troponina I ultrassensível: 8.200 pg/mL.",
    "Cateterismo de urgência: oclusão total trombótica da artéria descendente anterior proximal. ICP primária com stent farmacológico. FEVE pós-procedimento: 42%."
  ],
  clue_labels:["Desconforto torácico noturno","Irradiação e sintomas vegetativos","Fatores de risco e vitais","ECG e biomarcadores","Cateterismo (diagnóstico definitivo)"],
  explanation:"IAM com supra é emergência médica. O diagnóstico é eletrocardiográfico — supra de ST em derivações contíguas ou BRE novo. A reperfusão de escolha é ICP primária em até 90 min do primeiro contato médico (door-to-balloon). Anticoagulação e dupla antiagregação são pilares do tratamento.",
  reference:"SBC - Diretriz de Síndromes Coronarianas Agudas, 2021. Ibanez B et al. ESC Guidelines 2017.",difficulty:1},

  {id:6,diagnosis:"Acidente Vascular Cerebral Isquêmico",aliases:["avc isquêmico","avc","avci","isquemia cerebral"],cid:"I63",category:"Neurologia",
  clues:[
    "Mulher, 67 anos, é encontrada pelo marido pela manhã com dificuldade para falar e braço direito caído. Estava bem quando foram dormir às 23h.",
    "A fala é incompreensível — não consegue nomear objetos nem repetir frases. O marido percebe que o canto direito da boca está caído. Chega ao PS às 8h20.",
    "Histórico de fibrilação atrial diagnosticada há 2 anos, em uso irregular de warfarina ('tomo quando lembro'). Hipertensa. PA: 185/100 mmHg. Sem trauma recente.",
    "TC de crânio sem contraste: sem hemorragia. Hipodensidade incipiente em território de ACM esquerda (sinal precoce). NIHSS = 14. INR colhido: 1,3.",
    "Angiotomografia cerebral: oclusão de artéria cerebral média esquerda no segmento M1. Tempo porta-imagem: 28 min. Janela de 4h30 disponível. rt-PA administrado."
  ],
  clue_labels:["Déficit focal ao acordar","Caracterização do déficit","Histórico e anticoagulação","Neuroimagem e NIHSS","Angiotomografia (oclusão)"],
  explanation:"AVC isquêmico é emergência tempo-dependente. O onset ao acordar dificulta o cálculo da janela — considera-se o último momento visto normal. A FA com anticoagulação inadequada é fator de risco maior. A trombólise IV deve ser feita em até 4h30 se critérios preenchidos. Trombectomia mecânica até 24h em casos selecionados.",
  reference:"Pontes-Neto OM et al. Diretrizes Brasileiras de AVC. Arq Neuropsiquiatr 2009. Powers WJ et al. AHA/ASA 2019.",difficulty:2},

  {id:7,diagnosis:"Meningite Bacteriana",aliases:["meningite meningocócica","meningite por pneumococo","meningite"],cid:"G00",category:"Neurologia / Infectologia",
  clues:[
    "Adolescente, 17 anos, é trazido pelos pais ao PS às 2h da manhã com febre e 'a pior dor de cabeça da vida'. Vômitou duas vezes no caminho.",
    "Ao chegar: febre 40°C, fotofobia intensa, não consegue dobrar o pescoço. Está confuso e responde mal às perguntas. Glasgow 12.",
    "Estudante do 2º ano do ensino médio. Dois colegas de turma tiveram febre e internaram na semana passada. Nenhum foi vacinado contra meningococo B.",
    "Exame de pele: petéquias em pernas e tronco que aumentam de tamanho durante a avaliação. Punção lombar: LCR turvo, 2.400 células (98% neutrófilos), glicose 22 mg/dL, proteína 380 mg/dL.",
    "Gram do LCR: diplococos gram-negativos intracelulares. Cultura: Neisseria meningitidis sorogrupo B. PCR positivo. Hemocultura também positiva."
  ],
  clue_labels:["Cefaleia e febre aguda","Sinais meníngeos","Contexto epidemiológico","Exantema e liquor","Microbiologia confirmatória"],
  explanation:"Meningite meningocócica é emergência com risco de vida. A tríade febre + cefaleia + rigidez de nuca é clássica. A púrpura extensiva sugere meningococcemia com risco de choque. Penicilina cristalina deve ser iniciada imediatamente após a PL. Quimioprofilaxia dos contatos com rifampicina. Notificação imediata.",
  reference:"MS Brasil - Protocolo de Tratamento da Doença Meningocócica, 2019. van de Beek D et al. NEJM 2006.",difficulty:1},

  {id:8,diagnosis:"Apendicite Aguda",aliases:["apendicite","apendicite perfurada"],cid:"K35",category:"Cirurgia / Abdome Agudo",
  clues:[
    "Homem, 22 anos, procura UPA com dor abdominal que começou difusa há 18 horas. 'Parece cólica, mas não passa.' Sem diarreia, sem vômito até o momento.",
    "Nas últimas 6 horas a dor migrou para o lado direito do abdome e ficou localizada. Qualquer movimento piora. Surgem náuseas e vômito bilioso. Temperatura 38,1°C.",
    "Sem doenças prévias, sem cirurgias anteriores. Última refeição normal foi 24h atrás, mas perdeu o apetite. Nega ingesta de alimentos suspeitos.",
    "Exame: ponto de McBurney positivo, sinal de Blumberg positivo, psoas positivo. Leucócitos 14.800/mm³ com bastões 12%. PCR 48 mg/L. Score de Alvarado: 9.",
    "Ultrassonografia: apêndice com 12 mm de diâmetro, paredes espessadas, incompressível, com líquido livre periapendicular. TC confirmou sem perfuração."
  ],
  clue_labels:["Dor abdominal inespecífica","Migração e localização da dor","Histórico negativo relevante","Exame físico e laboratório","Imagem confirmatória"],
  explanation:"Apendicite aguda é a causa mais comum de abdome agudo cirúrgico. A migração da dor periumbilical para FID em horas é clássica. O escore de Alvarado ≥ 7 tem alta sensibilidade. A ultrassonografia é o primeiro exame de imagem; TC para casos duvidosos. Tratamento: apendicectomia laparoscópica com antibioticoprofilaxia.",
  reference:"Di Saverio S. WSES Guidelines 2020. Ferris M et al. Cochrane Review 2017.",difficulty:1},

  {id:9,diagnosis:"Cetoacidose Diabética",aliases:["cad","cetoacidose","descompensação diabética"],cid:"E11.1",category:"Endocrinologia",
  clues:[
    "Mulher, 19 anos, é trazida ao PS pelo namorado em estado de confusão e dificuldade para responder. Estava bem ontem à noite mas acordou muito mal.",
    "Ao exame: respiração rápida, profunda e ruidosa. Hálito com odor adocicado incomum. Mucosas secas, turgor cutâneo diminuído. PA 90/60 mmHg, FC 128 bpm, FR 32 irpm.",
    "Diabética tipo 1 desde os 12 anos. Namorado conta que ela ficou sem insulina por 3 dias por dificuldades financeiras. Não usou análogos alternativos.",
    "Glicemia: 487 mg/dL. Gasometria: pH 7,12, HCO₃ 8 mEq/L, pCO₂ 22 mmHg. Ânion gap: 24. Cetonúria 3+ na fita. Potássio sérico: 5,8 mEq/L.",
    "Cetonemia (beta-hidroxibutirato): 6,2 mmol/L. Diagnóstico de CAD grave confirmado pelos três critérios: hiperglicemia + acidose metabólica + cetonemia."
  ],
  clue_labels:["Rebaixamento de consciência","Respiração e exame físico","Histórico de omissão de insulina","Gasometria e glicemia","Cetonemia confirmatória"],
  explanation:"CAD é complicação aguda grave do DM tipo 1. A respiração de Kussmaul é compensação respiratória da acidose metabólica. Tríade: hiperglicemia + acidose + cetonemia. Tratamento: hidratação EV vigorosa, insulina regular EV após K > 3,5, reposição de K e tratar causa precipitante.",
  reference:"SBD - Diretrizes da Sociedade Brasileira de Diabetes 2022-2023. Kitabchi AE et al. Diabetes Care 2009.",difficulty:2},

  {id:10,diagnosis:"Pré-eclâmpsia",aliases:["pre-eclampsia","préeclâmpsia","hipertensão na gravidez"],cid:"O14",category:"Ginecologia e Obstetrícia",
  clues:[
    "Gestante, 24 anos, primigesta, 34 semanas, comparece ao pré-natal com queixa de inchaço nas mãos e rosto que piorou muito nos últimos 5 dias.",
    "Relata cefaleia occipital persistente 'como uma pressão na nuca' e episódios de 'luzes piscando' na visão. Pressão arterial: 158/102 mmHg em duas medições com 6h de intervalo.",
    "Gestação sem intercorrências até a 30ª semana. Sem histórico de hipertensão prévia. Mãe teve pré-eclâmpsia. Ganho de 4 kg na última semana.",
    "Proteinúria 24h: 780 mg. TGO/TGP 3x o limite. LDH 680 U/L. Plaquetas 98.000/mm³. Haptoglobina diminuída. Critérios de síndrome HELLP presentes.",
    "Doppler obstétrico: índice de resistência elevado em artérias uterinas e umbilicais. Crescimento fetal abaixo do percentil 10. Conduta: sulfato de magnésio e resolução da gestação."
  ],
  clue_labels:["Edema gestacional","Sintomas de alerta e PA","Histórico e fatores de risco","Laboratório (HELLP)","Doppler e conduta"],
  explanation:"Pré-eclâmpsia é definida por PA ≥ 140/90 mmHg após 20 semanas + proteinúria ou disfunção de órgão-alvo. A HELLP é complicação grave. Sintomas como cefaleia e escotomas indicam eminência de eclâmpsia. Tratamento definitivo: parto. Sulfato de magnésio para profilaxia de convulsões.",
  reference:"FEBRASGO - Pré-eclâmpsia. Diretrizes Clínicas 2018. ACOG Practice Bulletin 2020.",difficulty:2},

  {id:11,diagnosis:"Pneumonia Comunitária",aliases:["pneumonia","pac","pneumonia adquirida na comunidade"],cid:"J18",category:"Pneumologia",
  clues:[
    "Homem, 55 anos, procura UPA com febre e tosse produtiva há 4 dias. Inicialmente achava que era gripe mas piorou, com dor no peito que piora ao respirar fundo.",
    "Febre 38,8°C. Tosse com expectoração amarelo-esverdeada. Dispneia aos pequenos esforços desde ontem. Ausculta: crepitações em base direita com egofonia.",
    "Diabético tipo 2 há 8 anos, tabagista (20 maços-ano). FR 26 irpm, SatO₂ 93% em ar ambiente, FC 110 bpm. Está confuso e desorientado no tempo.",
    "Radiografia de tórax: consolidação lobar em lobo inferior direito com broncograma aéreo. Leucócitos 18.400/mm³ com desvio. PCR 148 mg/L. Ureia 52 mg/dL.",
    "Score CURB-65 = 3 (confusão + ureia > 50 + FR ≥ 30). Antígeno urinário de Streptococcus pneumoniae: positivo. Hemocultura coletada antes dos antibióticos."
  ],
  clue_labels:["Tosse e febre","Achados pulmonares","Comorbidades e gravidade","Imagem e laboratório","Score e agente etiológico"],
  explanation:"PAC é a 4ª causa de morte no Brasil. O CURB-65 estratifica a gravidade: ≥ 3 indica internação e possível UTI. O antígeno urinário de pneumococo é rápido e específico. Tratamento em internados: beta-lactâmico + macrolídeo. Iniciar antibiótico em até 4h do diagnóstico.",
  reference:"SBPT - Diretrizes Brasileiras de Pneumonia, 2009. Mandell LA et al. Clin Infect Dis 2007.",difficulty:1},

  {id:12,diagnosis:"Insuficiência Cardíaca Descompensada",aliases:["insuficiência cardíaca","ic descompensada","icc"],cid:"I50",category:"Cardiologia",
  clues:[
    "Homem, 72 anos, chega ao PS com falta de ar progressiva há 5 dias, piora ao deitar e inchaço nas pernas. Diz que 'o coração já era fraco antes'.",
    "Ganhou 4 kg na última semana. Precisa de 3 travesseiros para dormir. Acorda sufocando à noite. Em uso de enalapril e furosemida — mas parou de pesar diariamente.",
    "Histórico de doença de Chagas diagnosticada há 15 anos. Miocardiopatia dilatada chagásica conhecida. Ex-morador de zona rural no Nordeste. Nega etilismo.",
    "Exame: B3 presente, crepitações bibasais, turgência jugular a 45°, hepatomegalia dolorosa, edema 3+ em MMII. Rx tórax: cardiomegalia, linhas B de Kerley, derrame pleural bilateral. BNP = 1.840 pg/mL.",
    "Ecocardiograma: FEVE 28% (reduzida), dilatação de VE, insuficiência mitral funcional moderada, padrão diastólico restritivo — compatível com miocardiopatia dilatada avançada."
  ],
  clue_labels:["Dispneia progressiva","Retenção de fluidos","Histórico de cardiopatia chagásica","Exame físico e imagem","Ecocardiograma confirmatório"],
  explanation:"IC com FE reduzida é síndrome frequente. A etiologia chagásica é prevalente no Norte e Nordeste brasileiro. BNP > 400 pg/mL confirma descompensação. Tratamento: furosemida EV, IECA/BRA, betabloqueador, ARM e SGLT2i conforme tolerância. Monitorar balanço hídrico.",
  reference:"Rohde LE et al. Diretriz Brasileira de IC, 2018. McDonagh TA et al. ESC Guidelines 2021.",difficulty:2},

  {id:13,diagnosis:"Tromboembolia Pulmonar",aliases:["tep","embolia pulmonar","tromboembolismo pulmonar"],cid:"I26",category:"Pneumologia / Cardiologia",
  clues:[
    "Mulher, 45 anos, chega ao PS com falta de ar súbita que iniciou há 2 horas enquanto assistia TV. Nega febre. Refere dor no lado direito do peito que piora ao respirar.",
    "Tosse seca com escarros com sangue. SatO₂ 89% em ar ambiente. FC 118 bpm. Dor e inchaço em panturrilha esquerda há 3 dias, que ignorou.",
    "Submetida a artroplastia total de quadril há 8 dias. Ficou 5 dias no leito hospitalar sem profilaxia anticoagulante adequada por 'contraindicação documentada'.",
    "ECG: taquicardia sinusal, padrão S1Q3T3. Gasometria: PaO₂ 62 mmHg, hipocapnia. D-dímero > 4.000 ng/mL. Score de Wells: 7,5 (alta probabilidade). Eco: VD dilatado com McConnell positivo.",
    "Angiotomografia de tórax: defeitos de enchimento em artéria pulmonar principal direita e ramos lobares bilaterais. Doppler de MMII: TVP em veia poplítea esquerda confirmada."
  ],
  clue_labels:["Dispneia súbita","Hemoptise e sinais clínicos","Fator de risco cirúrgico","ECG, gasometria e escores","Angiotomografia (padrão-ouro)"],
  explanation:"TEP é emergência com mortalidade elevada se não tratada. A tríade clássica (dispneia + dor pleurítica + hemoptise) está presente em < 30% dos casos. O Wells estratifica probabilidade pré-teste. A angio-TC é o padrão-ouro. Tratamento: anticoagulação plena; trombólise em instabilidade hemodinâmica.",
  reference:"SBC - Diretriz de Embolia Pulmonar, 2016. Konstantinides SV et al. ESC Guidelines 2019.",difficulty:2},

  {id:14,diagnosis:"Malária por Plasmodium falciparum",aliases:["malária","malária falciparum","malária grave"],cid:"B50",category:"Infectologia",
  clues:[
    "Homem, 31 anos, dá entrada no PS com febre há 5 dias, calafrios, dor de cabeça intensa e vômitos repetidos. Está muito fraco e confuso.",
    "A febre não segue padrão fixo — não é terçã nem quartã, é contínua e alta (40°C). Está com icterícia discreta. Baço palpável a 3 cm do rebordo costal.",
    "Trabalhou em garimpo clandestino no interior do Pará nos últimos 2 meses. Retornou há 8 dias. Não realizou profilaxia antimalárica. Sem viagem internacional.",
    "Glasgow 12. Urina com coloração escura ('coca-cola'). Glicemia 48 mg/dL. Plaquetas 28.000/mm³. Bilirrubinas elevadas. Esfregaço de sangue: parasitemia > 5%.",
    "Teste rápido imunocromatográfico positivo para Plasmodium falciparum (HRP-2). PCR confirmatório positivo. Critérios OMS de malária grave presentes: malária cerebral + hipoglicemia + hiperparasitemia."
  ],
  clue_labels:["Síndrome febril inespecífica","Febre sem padrão e hepatoesplenomegalia","Exposição em área endêmica","Rebaixamento e hemoglobinúria","Teste rápido e PCR"],
  explanation:"Malária por P. falciparum é a forma mais grave, podendo causar morte em horas. A urina escura ('coca-cola') indica hemoglobinúria por hemólise grave. Critérios de gravidade OMS: coma, hiperparasitemia, hipoglicemia, IRA, edema pulmonar. Tratamento: artesunato EV. Notificação compulsória.",
  reference:"MS Brasil - Manual de Diagnóstico e Tratamento da Malária, 2020. WHO Guidelines, 3ª ed. 2015.",difficulty:3},

  {id:15,diagnosis:"Leishmaniose Visceral",aliases:["calazar","kala-azar","leishmaniose"],cid:"B55.0",category:"Infectologia",
  clues:[
    "Criança, 3 anos, levada à UPA com febre há 45 dias e barriga crescendo progressivamente. A mãe acha que está com 'verme no fígado'.",
    "A febre é irregular, às vezes sumia por dias e voltava. A criança está cada vez mais pálida, sem energia, e perdeu peso. Chora muito.",
    "Mora em município do interior do Maranhão. Cão da família morreu há 2 meses com feridas na pele e emagrecimento. Área com casos conhecidos de 'barriga d'água'.",
    "Exame físico: palidez 3+/4+, baço a 9 cm do RCE, fígado a 6 cm do RCD, adenopatia inguinal. Hemoglobina 5,8 g/dL, leucópenia, plaquetopenia. Albumina 2,2 g/dL. Hipergamaglobulinemia.",
    "Teste rápido rK39: positivo. Pesquisa de Leishmania em medula óssea: formas amastigotas intracelulares identificadas. Diagnóstico parasitológico confirmado."
  ],
  clue_labels:["Febre prolongada e hepatomegalia","Evolução da síndrome","Exposição em área endêmica","Pancitopenia e hipoalbuminemia","Mielograma confirmatório"],
  explanation:"Leishmaniose visceral (calazar) é endêmica no Nordeste. A tríade: febre prolongada + esplenomegalia + pancitopenia. O diagnóstico definitivo é parasitológico (aspirado de medula). O rK39 tem alta sensibilidade. Tratamento de 1ª linha: Anfotericina B lipossomal. Alta letalidade sem tratamento.",
  reference:"MS Brasil - Manual de Vigilância e Controle da LV, 2014. Chappuis F et al. Nat Rev Microbiol 2007.",difficulty:2},

  {id:16,diagnosis:"Hipotireoidismo Primário",aliases:["hipotireoidismo","tireoidite de hashimoto"],cid:"E03",category:"Endocrinologia",
  clues:[
    "Mulher, 38 anos, procura clínico geral com 'cansaço que não passa'. Há 8 meses acorda cansada, mesmo dormindo bem. Engordou 6 kg sem mudar a alimentação.",
    "Cabelo caindo em mechas, pele cada vez mais seca e áspera ao toque. Intestino preso há meses — evacuava diariamente, agora a cada 3–4 dias. Ciclo menstrual irregular.",
    "Sem doenças prévias. Mãe tem 'problema de tireoide'. Sensação constante de frio mesmo em ambiente quente. Raciocínio mais lento — sente que 'o pensamento trava'.",
    "FC 54 bpm. Reflexos tendinosos com relaxamento lentificado. Pele fria e pastosa. Edema facial não compressível. TSH = 28,4 mUI/L. T4 livre = 0,52 ng/dL.",
    "Anti-TPO: 1.200 U/mL (fortemente positivo). Ultrassonografia de tireoide: glândula hipotrófica, heterogênea, padrão pseudonodular difuso — compatível com tireoidite de Hashimoto."
  ],
  clue_labels:["Cansaço e ganho de peso","Sintomas sistêmicos","Histórico familiar e intolerância ao frio","Exame físico e TSH","Anti-TPO e imagem"],
  explanation:"Hipotireoidismo é a disfunção endócrina mais prevalente, mais comum em mulheres. O TSH é o exame mais sensível para triagem. Anti-TPO elevado confirma etiologia autoimune (Hashimoto). Tratamento: levotiroxina oral, com ajuste de dose a cada 4–6 semanas pelo TSH.",
  reference:"SBEM - Diretriz Brasileira para o Manejo do Hipotireoidismo, 2020. Jonklaas J et al. Thyroid 2014.",difficulty:1},

  {id:17,diagnosis:"Chikungunya",aliases:["febre chikungunya","artralgias chikungunya"],cid:"A92.0",category:"Infectologia",
  clues:[
    "Mulher, 52 anos, procura UBS com febre alta de início abrupto há 3 dias. Diz que 'veio do nada'. Está muito fraca e mal consegue andar.",
    "As articulações das mãos, punhos, tornozelos e pés estão dolorosas, com edema e rubor — bilateralmente. A dor é 10/10 e não cede com dipirona. Prefere ficar imóvel no leito.",
    "Mora no Rio de Janeiro. Município em surto de arbovirose declarado há 3 semanas. Vizinha com quadro semelhante. Nega viagem.",
    "Hemograma: leucopenia 2.800/mm³, linfocitose relativa. Plaquetas: 140.000/mm³ (não tão baixas quanto na dengue). Surgimento de exantema maculopapular no 3º dia, com áreas de pele poupada.",
    "IgM anti-chikungunya: positivo. RT-PCR em fase aguda positivo para vírus chikungunya. Dengue e Zika descartados por sorologia e PCR."
  ],
  clue_labels:["Febre aguda com incapacidade","Artralgia intensa e simétrica","Contexto de surto","Hemograma e exantema","Sorologia e PCR confirmatório"],
  explanation:"Chikungunya significa 'aquele que se dobra' — a artralgia é tão intensa que altera a postura. O diferencial com dengue é a poliartralgia incapacitante simétrica e as plaquetas menos afetadas. A forma crônica (artralgia > 3 meses) ocorre em 30–40%. Tratamento sintomático. Notificação compulsória.",
  reference:"MS Brasil - Chikungunya: manejo clínico, 2017. Burt FJ et al. Lancet 2017.",difficulty:2},

  {id:18,diagnosis:"Cirrose Hepática",aliases:["cirrose","cirrose descompensada","hepatopatia crônica"],cid:"K74",category:"Gastroenterologia",
  clues:[
    "Homem, 55 anos, admitido com barriga crescendo progressivamente há 3 semanas e amarelamento da pele. Está confuso e agitado à noite.",
    "Familiares relatam que ele bebe cachaça diariamente há mais de 20 anos, pelo menos uma garrafa por dia. Nas últimas semanas parou de beber mas piorou.",
    "Ao exame físico: eritema palmar, múltiplas telangiectasias em tórax, ginecomastia, circulação colateral abdominal visível ('cabeça de medusa'). Ascite volumosa com piparote positivo.",
    "Flapping tremor presente. Desorientado no tempo. Albumina 2,0 g/dL. Bilirrubina total 8,2 mg/dL. INR 2,4. Sódio 128 mEq/L. Child-Pugh C. MELD-Na = 22.",
    "Endoscopia: varizes esofágicas de grosso calibre com sinais de sangramento recente. Ultrassonografia: fígado nodular heterogêneo, esplenomegalia, hipertensão portal confirmada por Doppler."
  ],
  clue_labels:["Ascite e icterícia","Etiologia alcoólica","Estigmas hepáticos crônicos","Encefalopatia e scores de gravidade","Endoscopia e imagem"],
  explanation:"Cirrose hepática alcóolica é causa frequente no Brasil. As complicações maiores: hemorragia varicosa, encefalopatia, PBE, síndrome hepatorrenal e CHC. O MELD-Na estratifica urgência no transplante. Transplante hepático é o tratamento definitivo em casos selecionados.",
  reference:"SBH - Diretrizes Brasileiras de Cirrose Hepática, 2019. EASL Clinical Practice Guidelines 2018.",difficulty:2},

  {id:19,diagnosis:"Pancreatite Aguda",aliases:["pancreatite","pancreatite grave"],cid:"K85",category:"Cirurgia / Gastroenterologia",
  clues:[
    "Mulher, 44 anos, obesa, chega ao PS com dor intensa em região do estômago que iniciou súbito há 6 horas após jantar farto. É a pior dor que já sentiu.",
    "A dor se irradia 'em faixa' para o dorso e melhora um pouco quando ela se senta curvada para frente. Náuseas e vômitos que não aliviam a dor. Febre baixa: 37,8°C.",
    "Histórico de cálculos na vesícula diagnosticados há 6 meses — estava aguardando cirurgia. Não bebe álcool. Sem medicamentos novos recentemente.",
    "Amilase 1.840 U/L, lipase 2.200 U/L (> 3x o normal). Leucócitos 16.200/mm³. PCR 210 mg/L. Cálcio 7,8 mg/dL. Sinal de Cullen ausente mas Grey Turner discreto nos flancos.",
    "TC de abdome com contraste (protocolo de pâncreas): necrose em corpo e cauda, coleção peripancreática. Score CTSI (Balthazar) = 7 — pancreatite grave. UTI indicada."
  ],
  clue_labels:["Dor epigástrica súbita intensa","Irradiação e posição de alívio","Histórico de litíase biliar","Amilase, lipase e sinais físicos","Tomografia de gravidade"],
  explanation:"Pancreatite aguda: causas mais comuns são litíase biliar (60%) e álcool. Diagnóstico por 2 de 3 critérios: dor típica, enzimas > 3x, TC com achados. A lipase é mais específica que a amilase. O CTSI ≥ 7 indica necrose e alto risco. Tratamento: hidratação EV agressiva, analgesia, jejum.",
  reference:"Tenner S et al. Am J Gastroenterol 2013. IAP/APA Evidence-based Guidelines 2013.",difficulty:2},

  {id:20,diagnosis:"HIV / AIDS",aliases:["hiv","aids","síndrome da imunodeficiência adquirida","infecção por hiv"],cid:"B24",category:"Infectologia",
  clues:[
    "Homem, 32 anos, procura UBS com diarreia crônica há 2 meses, perda de peso importante e cansaço. 'Não tenho força para nada.'",
    "Perdeu 12 kg em 3 meses sem fazer dieta. Suores noturnos abundantes há 6 semanas. Apareceram manchas brancas na língua que raspam mas voltam.",
    "Relata relações sexuais sem preservativo com múltiplos parceiros. Não tem parceiro fixo. Nega uso de drogas injetáveis. Nunca testou para HIV.",
    "Adenopatia cervical e inguinal bilateral. Radiografia de tórax: infiltrado intersticial bilateral difuso. SpO₂ 91% em repouso. LDH 820 U/L. Teste rápido para HIV: positivo em dois algoritmos diferentes.",
    "Western Blot confirmatório: reagente. Carga viral HIV RNA: 480.000 cópias/mL. CD4: 78 células/mm³ (< 200 = AIDS). Lavado broncoalveolar: Pneumocystis jirovecii — pneumocistose confirmada."
  ],
  clue_labels:["Síndrome consuntiva","Candida oral e suores","Histórico comportamental","Achados radiológicos e teste rápido","CD4 e infecção oportunista"],
  explanation:"HIV/AIDS com CD4 < 200 células/mm³ define AIDS. A PCP é a infecção oportunista mais comum nesse estágio. Diagnóstico de HIV por teste rápido em algoritmo duplo + confirmação por Western Blot. A TARV deve ser iniciada o mais cedo possível. Profilaxia primária com SMX-TMP quando CD4 < 200.",
  reference:"MS Brasil - PCDT para Manejo da Infecção pelo HIV em Adultos, 2022. WHO Consolidated Guidelines 2021.",difficulty:2},

  {id:21,diagnosis:"Febre Tifoide",aliases:["tifoide","febre entérica"],cid:"A01.0",category:"Infectologia",
  clues:[
    "Jovem de 19 anos, retornou há 10 dias de viagem a município rural no Nordeste. Febre há 8 dias que foi aumentando gradualmente — começou com 37,8°C e agora atinge 39,5°C.",
    "Apesar da febre alta, o coração está lento (FC 64 bpm) — o médico estranha essa 'bradicardia relativa'. Diarreia com 4–5 episódios/dia na 1ª semana, substituída por constipação.",
    "Bebeu água de poço e comeu alimentos de barraquinha durante a viagem. Não foi vacinado contra febre tifoide. Familiares em casa estão bem.",
    "Exame físico: esplenomegalia palpável, manchas róseas no tronco (roséolas tíficas). Leucócitos 3.100/mm³ (leucopenia com eosinopenia). TGO/TGP levemente elevadas.",
    "Hemocultura (coletada na 1ª semana): positiva para Salmonella enterica sorovar Typhi. Coprocultura também positiva. Widal com soroaglutininas O e H em títulos significativos."
  ],
  clue_labels:["Febre gradual pós-viagem","Dissociação pulso-temperatura","Exposição hídrica e alimentar","Roséolas tíficas e leucopenia","Hemocultura confirmatória"],
  explanation:"Febre tifoide é causada por Salmonella Typhi — transmissão fecal-oral por água ou alimento contaminado. A dissociação pulso-temperatura (bradicardia relativa) é clássica. Roséolas tíficas são patognomônicas. A hemocultura na 1ª semana tem a maior sensibilidade. Tratamento: ciprofloxacino ou azitromicina.",
  reference:"Bhutta ZA et al. Typhoid fever. N Engl J Med 2006. MS Brasil - Manual de Controle das DTAs.",difficulty:2},

  {id:22,diagnosis:"Acidente Vascular Cerebral Hemorrágico",aliases:["avc hemorrágico","avch","hemorragia cerebral","hemorragia intraparenquimatosa"],cid:"I61",category:"Neurologia",
  clues:[
    "Homem, 61 anos, cai repentinamente em casa durante uma discussão acalorada. Esposa chama SAMU — ele está com braço e perna esquerdos sem movimento e não reconhece onde está.",
    "Relata ter tido 'a pior dor de cabeça da vida' antes de cair. PA na chegada: 210/120 mmHg. Glasgow 10. Desvio do olhar conjugado para a direita.",
    "Hipertenso há 15 anos, em uso irregular de losartana. Parou de medir a pressão há 6 meses. Nega anticoagulantes, nega trauma. Etilista social.",
    "TC de crânio sem contraste: hiperdensidade espontânea em núcleo lentiforme direito, volume 35 mL. Sem hidrocefalia. NIHSS 18. Sem desvio de linha média.",
    "Angiotomografia cerebral: sem malformação arteriovenosa ou aneurisma rotos. Sinal do ponto (spot sign) presente no hematoma — prediz expansão ativa e pior prognóstico."
  ],
  clue_labels:["Déficit focal súbito","Cefaleia e PA extrema","Histórico de HAS não controlada","Neuroimagem e NIHSS","Angiotomografia (spot sign)"],
  explanation:"Hemorragia intraparenquimatosa representa 15–20% dos AVCs. A HAS não controlada é o principal fator de risco (localização clássica: núcleos da base). O controle pressórico imediato (< 140 mmHg) reduz expansão. O spot sign na angiotomografia prediz crescimento do hematoma e pior desfecho.",
  reference:"AHA/ASA Guidelines for ICH 2022. Pontes-Neto OM. Arq Neuropsiquiatr 2009.",difficulty:3},

  {id:23,diagnosis:"Síndrome de Burnout",aliases:["burnout","esgotamento profissional"],cid:"Z73.0",category:"Saúde Mental / Medicina do Trabalho",
  clues:[
    "Médico residente de 2º ano, 27 anos, procura psiquiatra com 'cansaço que não passa'. Há 4 meses acorda exausto, mesmo nos dias de folga. Insônia de manutenção.",
    "Dificuldade de concentração crescente. Choro sem motivo aparente. Sente que 'não se importa mais com os pacientes' — algo que o perturba profundamente.",
    "Faz 3 plantões de 24h por semana além das atividades ambulatoriais. Sente que o trabalho 'não faz diferença'. Recentemente cometeu erro de prescrição — nunca havia acontecido.",
    "Questionário de Maslach (MBI): escore 48/54 em Exaustão Emocional (muito alto), 22/30 em Despersonalização (alto), 12/48 em Realização Pessoal (muito baixo). Sem episódio depressivo maior anterior.",
    "Avaliação psiquiátrica: ausência de transtorno depressivo maior, bipolar ou ansioso — os sintomas estão estritamente vinculados ao contexto ocupacional. CID-11 Z73.0: Síndrome de Burnout — fenômeno ocupacional."
  ],
  clue_labels:["Exaustão persistente","Despersonalização","Carga de trabalho e impacto funcional","Escala de Maslach (MBI)","Diagnóstico diferencial e CID-11"],
  explanation:"Burnout tem prevalência de 30–50% entre médicos residentes no Brasil. A CID-11 (2019) classificou como fenômeno ocupacional — não é transtorno mental, mas requer intervenção. O MBI avalia 3 dimensões: exaustão, despersonalização e realização pessoal. Tratamento: redução de carga, psicoterapia, suporte institucional.",
  reference:"CFM - Resolução 2.232/2019. WHO CID-11. West CP et al. JAMA 2018.",difficulty:3},

  {id:24,diagnosis:"Síndrome Coronariana Aguda sem Supra de ST",aliases:["scassst","angina instável","iam sem supra","iamssst"],cid:"I21.4",category:"Cardiologia",
  clues:[
    "Mulher, 62 anos, procura PS com 'aperto no peito' que ocorreu 3 vezes nas últimas 24h, durando 15–20 minutos cada episódio. Entre os episódios se sente bem.",
    "A dor aparece em repouso, sem esforço precipitante. Cede espontaneamente. Associada à falta de ar. Nega febre, nega tosse. PA: 150/90 mmHg. FC: 88 bpm. Ausculta normal.",
    "Hipertensa há 10 anos, dislipidêmica em uso de sinvastatina. Menopausada. Mãe faleceu de infarto aos 68 anos. Nega tabagismo. Sedentária.",
    "ECG: infradesnivelamento de ST de 1,5 mm em V4–V6 que retorna ao normal entre os episódios. Troponina T ultrassensível admissão: 52 ng/L; 3h depois: 128 ng/L (delta positivo). Score GRACE: 142.",
    "Coronariografia: lesão obstrutiva de 85% em artéria circunflexa proximal — culprit lesion identificada. ICP com stent farmacológico. Ecocardiograma pós: FEVE 58%, sem alterações segmentares."
  ],
  clue_labels:["Dor torácica episódica em repouso","Características da dor","Fatores de risco cardiovascular","ECG e troponina seriada","Coronariografia confirmatória"],
  explanation:"SCA sem supra engloba angina instável (sem elevação de troponina) e IAM sem supra (troponina elevada). O delta de troponina confirma lesão miocárdica. Score GRACE > 140 = alto risco: coronariografia em < 24h. Tratamento: dupla antiagregação + anticoagulação + estatina de alta intensidade.",
  reference:"SBC - Diretriz de SCA sem Supra de ST, 2021. Collet JP et al. ESC Guidelines 2020.",difficulty:3},

  {id:25,diagnosis:"Hipertensão Arterial Sistêmica",aliases:["has","hipertensão arterial","hipertensão","pressão alta"],cid:"I10",category:"Cardiologia",
  clues:[
    "Mulher, 48 anos, vai ao médico para check-up anual. Não tem queixas. A pressão medida na consulta é 158/98 mmHg — técnica correta, após 5 min de repouso.",
    "Médico repete a medição antes de sair: 155/96 mmHg. Há 3 meses, em outra consulta, foi registrada 152/94 mmHg. A paciente dizia que 'pressão alta é coisa de velho'.",
    "Sedentária, IMC 32 kg/m², tabagista (10 cigarros/dia há 15 anos). Pai faleceu de IAM aos 55 anos. Mãe hipertensa. Ingere sal em excesso. Bebe álcool socialmente.",
    "ECG: índice de Sokolow-Lyon > 35 mm (sobrecarga ventricular esquerda). Ecocardiograma: hipertrofia concêntrica de VE (espessura de parede posterior 12 mm). Fundo de olho: cruzamentos AV grau II.",
    "Laboratório: microalbuminúria positiva (68 mg/g de creatinina), creatinina 0,9 mg/dL, glicemia 108 mg/dL, colesterol total 218 mg/dL. Lesão de órgão-alvo em 3 sítios: coração, olho e rim."
  ],
  clue_labels:["PA elevada assintomática","Confirmação da elevação","Fatores de risco múltiplos","Lesão cardíaca e ocular","Microalbuminúria renal"],
  explanation:"HAS afeta 36% dos adultos brasileiros e é a principal causa de morte cardiovascular. O diagnóstico requer 2 medidas elevadas em 2 ocasiões. A presença de lesão de órgão-alvo (coração, rim, olho) classifica como risco cardiovascular alto. Tratamento: mudança de estilo de vida + farmacoterapia (tiazídico, IECA/BRA, BCC).",
  reference:"SBC - 7ª Diretriz Brasileira de HAS, 2016. SBH/SBC - Diretriz Brasileira de HAS, 2020.",difficulty:1}
];

const ALL_DIAGNOSES = [
  // ── INFECTOLOGIA ──────────────────────────────────────────────
  "Dengue","Dengue Grave","Leptospirose","Doença de Chagas","Doença de Chagas Aguda",
  "Tuberculose Pulmonar","Tuberculose Miliar","Tuberculose Extrapulmonar","Tuberculose Ganglionar",
  "Tuberculose Meníngea","Tuberculose Óssea","Tuberculose Intestinal",
  "HIV / AIDS","Síndrome Retroviral Aguda","Pneumocistose","Toxoplasmose Cerebral",
  "Criptococose","Histoplasmose","Paracoccidioidomicose","Candidíase Invasiva","Candidemia",
  "Aspergilose Invasiva","Mucormicose","Coccidioidomicose","Esporotricose",
  "Malária por Plasmodium falciparum","Malária por Plasmodium vivax","Malária por Plasmodium malariae",
  "Leishmaniose Visceral","Leishmaniose Tegumentar","Leishmaniose Cutânea","Leishmaniose Mucocutânea",
  "Febre Tifoide","Febre Amarela","Febre Maculosa Brasileira","Febre de Chikungunya",
  "Chikungunya","Zika","Dengue com Sinais de Alarme",
  "Linfadenite Tuberculosa","Mononucleose Infecciosa","Citomegalovirose","Herpes Simples",
  "Herpes Zóster","Herpes Zóster Oftálmico","Varicela","Sarampo","Rubéola","Caxumba",
  "Coqueluche","Difteria","Tétano","Tétano Neonatal","Raiva","Hantavirose",
  "Leptospirose Grave (Síndrome de Weil)","Brucelose","Rickettsiose",
  "Febre por Arranhadura de Gato","Bartonela","Toxoplasmose",
  "Neurocisticercose","Equinococose","Esquistossomose","Esquistossomose Hepatoesplênica",
  "Ascaridíase","Estrongiloidíase","Ancilostomíase","Tricuríase","Enterobíase",
  "Giardíase","Amebíase","Criptosporidiose","Microsporidiose","Isosporíase",
  "Meningite Bacteriana","Meningite Tuberculosa","Meningite Viral","Meningite Fúngica",
  "Meningococcemia","Sepse Meningocócica","Encefalite Herpética","Encefalite por Arbovírus",
  "Endocardite Infecciosa","Osteomielite","Artrite Séptica","Celulite","Erisipela",
  "Fasciite Necrotizante","Abscesso de Partes Moles","Síndrome do Choque Tóxico",
  "Pneumonia Comunitária","Pneumonia Hospitalar","Pneumonia por Aspiração",
  "Pneumonia por Pneumocystis jirovecii","Empiema Pleural",
  "Pielonefrite","Cistite","Uretrite","Uretrite Gonocócica","Uretrite Não Gonocócica",
  "Sífilis","Sífilis Primária","Sífilis Secundária","Sífilis Terciária","Neurossífilis",
  "Gonorreia","Clamídia","Cancro Mole","Linfogranuloma Venéreo","Donovanose",
  "Hepatite A","Hepatite B","Hepatite C","Hepatite D","Hepatite E",
  "Hepatite B Crônica","Hepatite C Crônica","Hepatite Autoimune",
  "Infecção por HTLV","Infecção por EBV","Infecção por CMV",
  "Gripe (Influenza)","COVID-19","COVID-19 Grave","Síndrome Pós-COVID",
  "Infecção por VSR","Bronquiolite Viral","Laringite Viral","Sinusite Bacteriana",
  "Otite Média Aguda","Mastoidite","Abscesso Peritonsilar","Amigdalite Bacteriana",
  "Abscessos Hepáticos Amebianos","Abscesso Hepático Piogênico",
  "Peritonite Bacteriana Espontânea","Colangite Aguda","Colecistite Aguda",
  "Diverticulite","Tifo Murino","Leptospirose Pulmonar","Síndrome Pulmonar por Hantavírus",

  // ── CARDIOLOGIA ───────────────────────────────────────────────
  "Infarto Agudo do Miocárdio com Supra de ST","Infarto Agudo do Miocárdio sem Supra de ST",
  "Síndrome Coronariana Aguda sem Supra de ST","Angina Instável","Angina Estável",
  "Angina de Prinzmetal","Insuficiência Cardíaca Aguda","Insuficiência Cardíaca Crônica",
  "Insuficiência Cardíaca Descompensada","Insuficiência Cardíaca com FE Reduzida",
  "Insuficiência Cardíaca com FE Preservada",
  "Hipertensão Arterial Sistêmica","Crise Hipertensiva","Emergência Hipertensiva",
  "Urgência Hipertensiva","Hipertensão Resistente","Hipertensão Secundária",
  "Dissecção Aórtica","Dissecção Aórtica Tipo A","Dissecção Aórtica Tipo B",
  "Aneurisma de Aorta Abdominal","Aneurisma de Aorta Torácica","Rotura de Aneurisma de Aorta",
  "Fibrilação Atrial","Flutter Atrial","Taquicardia Supraventricular",
  "Taquicardia Ventricular","Fibrilação Ventricular","Torsades de Pointes",
  "Bradiarritmia","Bloqueio Atrioventricular Total","Bloqueio AV de 2º Grau","BAVT",
  "Síndrome do Seio Doente","Bloqueio de Ramo Esquerdo","Bloqueio de Ramo Direito",
  "Síndrome de Wolff-Parkinson-White","Síndrome de Brugada","Síndrome do QT Longo",
  "Parada Cardiorrespiratória","Morte Súbita Cardíaca",
  "Estenose Aórtica","Insuficiência Aórtica","Estenose Mitral","Insuficiência Mitral",
  "Prolapso de Válvula Mitral","Estenose Tricúspide","Insuficiência Tricúspide",
  "Insuficiência Pulmonar","Estenose Pulmonar",
  "Miocardite","Miocardiopatia Dilatada","Miocardiopatia Hipertrófica",
  "Miocardiopatia Restritiva","Miocardiopatia Chagásica","Miocardiopatia Periparto",
  "Miocardiopatia Alcoólica","Miocardiopatia por Estresse (Takotsubo)",
  "Pericardite Aguda","Pericardite Constritiva","Tamponamento Cardíaco",
  "Derrame Pericárdico","Endocardite de Libman-Sacks",
  "Tromboembolia Pulmonar","Hipertensão Pulmonar","Cor Pulmonale",
  "Mixoma Atrial","Trombo Intracardíaco","Doença de Kawasaki",
  "Coarctação da Aorta","Comunicação Interatrial","Comunicação Interventricular",
  "Persistência do Canal Arterial","Tetralogia de Fallot","Síndrome de Eisenmenger",
  "Doença de Buerger","Arterite de Takayasu","Arterite de Células Gigantes",
  "Trombose Venosa Profunda","Tromboflebite Superficial","Síndrome Pós-Trombótica",
  "Insuficiência Venosa Crônica","Úlcera Venosa","Isquemia Arterial Aguda dos Membros",
  "Doença Arterial Periférica","Claudicação Intermitente",

  // ── NEUROLOGIA ────────────────────────────────────────────────
  "Acidente Vascular Cerebral Isquêmico","Acidente Vascular Cerebral Hemorrágico",
  "Hemorragia Subaracnóidea","Hematoma Subdural","Hematoma Epidural",
  "Hematoma Subdural Crônico","Hemorragia Intraparenquimatosa",
  "Ataque Isquêmico Transitório","AIT","Trombose Venosa Cerebral",
  "Epilepsia","Estado de Mal Epiléptico","Crise Convulsiva Febril","Epilepsia Focal",
  "Epilepsia Generalizada","Síndrome de West","Síndrome de Lennox-Gastaut",
  "Esclerose Múltipla","Neuromielite Óptica","Síndrome Clínica Isolada",
  "Doença de Parkinson","Parkinsonismo Secundário","Tremor Essencial",
  "Doença de Alzheimer","Demência Vascular","Demência com Corpos de Lewy",
  "Demência Frontotemporal","Demência por HIV","Doença de Creutzfeldt-Jakob",
  "Síndrome de Guillain-Barré","Miastenia Gravis","Crise Miastênica",
  "Esclerose Lateral Amiotrófica","Atrofia Muscular Espinal",
  "Neuropatia Diabética","Polineuropatia","Mononeuropatia","Síndrome do Túnel do Carpo",
  "Síndrome do Túnel Cubital","Neuropatia por Hanseníase",
  "Meningite","Encefalite","Abscesso Cerebral","Empiema Subdural",
  "Neurossífilis","Neurocisticercose","Neuroesquistossomose",
  "Enxaqueca","Cefaleia em Salvas","Cefaleia Tensional",
  "Cefaleia por Uso Excessivo de Medicamento","Cefaleia Intracraniana Idiopática",
  "Hipertensão Intracraniana Idiopática","Síndrome de Hipertensão Intracraniana",
  "Hidrocefalia","Hidrocefalia de Pressão Normal",
  "Síndrome de Horner","Paralisia de Bell","Paralisia Facial Periférica",
  "Oftalmoplegia Internuclear","Síndrome de Miller Fisher",
  "Síndrome Cerebelar","Ataxia","Ataxia de Friedreich","Doença de Huntington",
  "Distonia","Coréia de Sydenham","Síndrome das Pernas Inquietas",
  "Narcolepsia","Síndrome da Apneia Obstrutiva do Sono","Insônia Crônica",
  "Delirium","Delirium Hiperativo","Delirium Hipoativo","Coma",
  "Morte Encefálica","Síndrome do Encarceramento","Estado Vegetativo",
  "Síndrome de Wernicke-Korsakoff","Encefalopatia Hepática","Encefalopatia Urêmica",
  "Encefalopatia Hipertensiva","Encefalopatia de Hashimoto",
  "Mielite Transversa","Siringomielia","Síndrome da Cauda Equina",
  "Compressão Medular","Hérnia de Disco Cervical","Hérnia de Disco Lombar",
  "Estenose de Canal Lombar","Radiculopatia Cervical","Radiculopatia Lombar",

  // ── PNEUMOLOGIA ───────────────────────────────────────────────
  "DPOC","DPOC Agudizado","Asma","Asma Grave","Asma Aguda",
  "Bronquiectasia","Fibrose Cística","Bronquite Crônica","Enfisema Pulmonar",
  "Pneumotórax","Pneumotórax Hipertensivo","Hemotórax","Derrame Pleural",
  "Pneumonia Comunitária","Pneumonia Atípica","Legionela","Pneumonia por Micoplasma",
  "Fibrose Pulmonar Idiopática","Pneumonia Intersticial","Pneumonia Eosinofílica",
  "Sarcoidose","Silicose","Asbestose","Pneumoconiose","Beriliose",
  "Doença Pulmonar Ocupacional","Pneumonite por Hipersensibilidade","Pulmão de Fazendeiro",
  "Síndrome do Desconforto Respiratório Agudo","SDRA","Insuficiência Respiratória Aguda",
  "Edema Agudo de Pulmão","Hipertensão Pulmonar","Cor Pulmonale",
  "Embolia Pulmonar","Infarto Pulmonar","Vasculite Pulmonar",
  "Câncer de Pulmão","Adenocarcinoma de Pulmão","Carcinoma de Células Escamosas",
  "Carcinoma de Pequenas Células","Mesotelioma","Nódulo Pulmonar Solitário",
  "Derrame Pleural Maligno","Tumor de Pancoast",
  "Rinite Alérgica","Sinusite Crônica","Polipose Nasal","Apneia do Sono",
  "Doença Pulmonar por Micobactéria Não Tuberculosa",

  // ── GASTROENTEROLOGIA ─────────────────────────────────────────
  "Úlcera Péptica","Úlcera Duodenal","Úlcera Gástrica","Gastrite Crônica",
  "Gastrite por H. pylori","Doença do Refluxo Gastroesofágico","Esofagite Erosiva",
  "Esôfago de Barrett","Acalasia","Espasmo Esofágico Difuso",
  "Doença de Crohn","Retocolite Ulcerativa","Colite Isquêmica","Colite Microscópica",
  "Colite por Clostridioides difficile","Íleo Paralítico","Oclusão Intestinal",
  "Intussuscepção","Vólvulo","Doença Diverticular","Diverticulite Aguda",
  "Hemorragia Digestiva Alta","Hemorragia Digestiva Baixa","Varizes Esofágicas",
  "Síndrome de Mallory-Weiss","Síndrome de Boerhaave",
  "Cirrose Hepática","Cirrose Biliar Primária","Colangite Esclerosante Primária",
  "Hepatite Alcoólica","Doença Hepática Gordurosa Não Alcoólica","Esteatohepatite Não Alcoólica",
  "Insuficiência Hepática Aguda","Encefalopatia Hepática","Síndrome Hepatorrenal",
  "Ascite","Peritonite Bacteriana Espontânea","Síndrome Hepatopulmonar",
  "Hipertensão Portal","Esplenomegalia Congestiva",
  "Pancreatite Aguda","Pancreatite Crônica","Pseudocisto Pancreático",
  "Necrose Pancreática","Câncer de Pâncreas","Insulinoma","Gastrinoma",
  "Colecistite Aguda","Colecistite Crônica","Colelitíase","Coledocolitíase",
  "Colangite Aguda","Colangite Esclerosante","Colestase",
  "Apendicite Aguda","Peritonite","Hérnia Inguinal","Hérnia Femoral",
  "Hérnia Umbilical","Hérnia Incisional","Hérnia Encarcerada","Hérnia Estrangulada",
  "Câncer Gástrico","Câncer Colorretal","Câncer de Esôfago","Câncer Hepatocelular",
  "Adenoma Hepático","Hemangioma Hepático","Cisto Hepático",
  "Síndrome do Intestino Irritável","Constipação Crônica","Megacólon Tóxico",
  "Isquemia Mesentérica","Angiodisplasia","Pólipo Colônico","Polipose Adenomatosa Familiar",
  "Doença Celíaca","Intolerância à Lactose","Má Absorção Intestinal",
  "Síndrome de Dumping","Síndrome do Intestino Curto",
  "Hemorroidas","Fissura Anal","Fístula Anal","Abscesso Perianal","Prolapso Retal",

  // ── ENDOCRINOLOGIA ────────────────────────────────────────────
  "Diabetes Mellitus Tipo 1","Diabetes Mellitus Tipo 2","Diabetes LADA","Diabetes MODY",
  "Diabetes Gestacional","Cetoacidose Diabética","Estado Hiperglicêmico Hiperosmolar",
  "Hipoglicemia","Hipoglicemia Grave","Insulinoma",
  "Hipotireoidismo Primário","Hipotireoidismo Secundário","Hipotireoidismo Congênito",
  "Hipotireoidismo Subclínico","Hipertireoidismo","Doença de Graves",
  "Tireoidite de Hashimoto","Tireoidite de De Quervain","Tireoidite Silenciosa",
  "Bócio Multinodular","Nódulo Tireoidiano","Câncer de Tireoide","Carcinoma Papilífero",
  "Carcinoma Folicular de Tireoide","Carcinoma Medular de Tireoide",
  "Carcinoma Anaplásico de Tireoide","Tempestade Tireoidiana","Coma Mixedematoso",
  "Hiperparatireoidismo Primário","Hiperparatireoidismo Secundário","Hipoparatireoidismo",
  "Hipercalcemia","Hipocalcemia","Osteoporose","Osteomalácia","Raquitismo",
  "Doença de Paget Óssea",
  "Síndrome de Cushing","Doença de Cushing","Insuficiência Adrenal","Doença de Addison",
  "Hiperplasia Adrenal Congênita","Feocromocitoma","Paraganglioma",
  "Hiperaldosteronismo Primário","Síndrome de Conn","Hiperaldosteronismo Secundário",
  "Acromegalia","Gigantismo","Nanismo Hipofisário","Deficiência de GH",
  "Hiperprolactinemia","Prolactinoma","Adenoma Hipofisário","Craniofaringioma",
  "Pan-hipopituitarismo","Diabetes Insipidus","SIADH","Hiponatremia",
  "Hipernatremia","Hipopotassemia","Hiperpotassemia","Síndrome de Realimentação",
  "Obesidade","Síndrome Metabólica","Dislipidemia","Hipertrigliceridemia",
  "Hipercolesterolemia Familiar","Síndrome dos Ovários Policísticos",
  "Ginecomastia","Amenorreia Primária","Amenorreia Secundária","Menopausa Precoce",
  "Hipogonadismo Masculino","Criptorquidia",

  // ── NEFROLOGIA ────────────────────────────────────────────────
  "Insuficiência Renal Aguda","Necrose Tubular Aguda","Nefrite Intersticial Aguda",
  "Nefrotoxicidade por Contraste","Insuficiência Renal Crônica","Doença Renal Crônica",
  "Doença Renal Crônica Estágio 5","Síndrome Nefrótica","Síndrome Nefrítica",
  "Glomerulonefrite","Glomerulonefrite por IgA","Doença de Berger",
  "Glomerulonefrite Rapidamente Progressiva","Glomerulonefrite Membranosa",
  "Glomerulonefrite Membranoproliferativa","Doença de Lesão Mínima",
  "Glomeruloesclerose Segmentar e Focal","Amiloidose Renal","Nefropatia Lúpica",
  "Nefropatia Diabética","Nefroesclerose Hipertensiva",
  "Pielonefrite Aguda","Pielonefrite Crônica","Pielonefrite Xantogranulomatosa",
  "Cistite","Cistite Intersticial","Prostatite","Epididimite","Orquite",
  "Cólica Renal","Nefrolitíase","Urolitíase","Obstrução Ureteral",
  "Hidronefrose","Bexiga Neurogênica","Incontinência Urinária",
  "Hiperplasia Prostática Benigna","Câncer de Próstata","Câncer de Rim",
  "Carcinoma de Células Renais","Câncer de Bexiga","Tumor de Wilms",
  "Doença Renal Policística","Doença Renal Policística Autossômica Dominante",
  "Síndrome de Alport","Síndrome de Bartter","Síndrome de Gitelman",
  "Acidose Tubular Renal","Hipercalciúria","Acidose Metabólica","Alcalose Metabólica",
  "Acidose Respiratória","Alcalose Respiratória",
  "Síndrome Urêmica","Pericardite Urêmica","Encefalopatia Urêmica",

  // ── REUMATOLOGIA ──────────────────────────────────────────────
  "Lúpus Eritematoso Sistêmico","Artrite Reumatoide","Espondiloartrite Anquilosante",
  "Espondilite Anquilosante","Artrite Psoriásica","Artrite Reativa","Síndrome de Reiter",
  "Artrite Enteropática","Síndrome de Sjögren","Esclerose Sistêmica","Esclerodermia",
  "Polimiosite","Dermatomiosite","Miosite por Corpos de Inclusão",
  "Síndrome Antifosfolipídeo","Vasculite","Poliarterite Nodosa",
  "Granulomatose com Poliangiite","Doença de Wegener","Poliangiite Microscópica",
  "Granulomatose Eosinofílica com Poliangiite","Síndrome de Churg-Strauss",
  "Arterite de Takayasu","Arterite de Células Gigantes","Arterite Temporal",
  "Doença de Behçet","Policondrite Recidivante","Síndrome de Cogan",
  "Gota","Pseudogota","Artrite por Cristais de Pirofosfato",
  "Artrose","Osteoartrite","Artropatia por Cristais","Artrite Gotosa",
  "Fibromialgia","Síndrome de Fadiga Crônica","Polimialgia Reumática",
  "Síndrome de Raynaud","Fenômeno de Raynaud","Miopatia Inflamatória",
  "Síndrome Hipereosinofílica","Mastocitose Sistêmica","Sarcoidose",
  "Síndrome Overlap","Doença Mista do Tecido Conjuntivo",

  // ── HEMATOLOGIA / ONCOLOGIA ───────────────────────────────────
  "Anemia Ferropriva","Anemia por Deficiência de Vitamina B12","Anemia por Deficiência de Folato",
  "Anemia Hemolítica Autoimune","Anemia Aplásica","Anemia de Doença Crônica",
  "Anemia Falciforme","Talassemia","Talassemia Maior","Talassemia Minor",
  "Esferocitose Hereditária","Deficiência de G6PD","Hemoglobinúria Paroxística Noturna",
  "Policitemia Vera","Trombocitemia Essencial","Mielofibrose","Síndrome Mielodisplásica",
  "Leucemia Mieloide Aguda","Leucemia Mieloide Crônica","Leucemia Linfoide Aguda",
  "Leucemia Linfoide Crônica","Leucemia de Células Pilosas","Leucemia Pró-linfocítica",
  "Linfoma de Hodgkin","Linfoma Não Hodgkin","Linfoma Difuso de Grandes Células B",
  "Linfoma Folicular","Linfoma de Burkitt","Linfoma de Células do Manto",
  "Linfoma de Células T","Linfoma Anaplásico","Linfoma Primário do SNC",
  "Mieloma Múltiplo","Plasmocitoma","Macroglobulinemia de Waldenström",
  "Amiloidose","Coagulação Intravascular Disseminada","CIVD",
  "Púrpura Trombocitopênica Imune","Trombocitopenia Induzida por Heparina",
  "Síndrome Hemolítico-Urêmica","Púrpura Trombocitopênica Trombótica",
  "Hemofilia A","Hemofilia B","Doença de Von Willebrand",
  "Trombocitopenia","Trombocitose","Neutropenia Febril","Agranulocitose",
  "Pancitopenia","Esplenomegalia","Linfadenopatia",
  "Câncer de Mama","Câncer de Colo do Útero","Câncer de Endométrio","Câncer de Ovário",
  "Câncer de Próstata","Câncer de Rim","Câncer de Bexiga","Câncer Testicular",
  "Câncer de Pulmão","Câncer Gástrico","Câncer Colorretal","Câncer de Esôfago",
  "Câncer Hepatocelular","Câncer de Pâncreas","Câncer de Tireoide","Câncer de Pele",
  "Melanoma","Carcinoma Basocelular","Carcinoma Espinocelular",
  "Glioblastoma","Glioma","Meningioma","Neurinoma do Acústico","Schwannoma",
  "Tumor Carcinoide","Tumor Neuroendócrino","Feocromocitoma","Neuroblastoma",
  "Sarcoma de Ewing","Osteossarcoma","Condrossarcoma","Sarcoma de Partes Moles",
  "Câncer de Cabeça e Pescoço","Carcinoma de Nasofaringe","Câncer de Laringe",
  "Síndrome da Veia Cava Superior","Compressão Medular Maligna",
  "Hipercalcemia Maligna","Síndrome de Lise Tumoral",

  // ── GINECOLOGIA E OBSTETRÍCIA ─────────────────────────────────
  "Pré-eclâmpsia","Eclâmpsia","Síndrome HELLP","Hipertensão Gestacional",
  "Diabetes Gestacional","Colestase Intra-hepática da Gravidez",
  "Gravidez Ectópica","Descolamento Prematuro de Placenta","Placenta Prévia",
  "Rotura Uterina","Vasa Prévia","Acretismo Placentário",
  "Aborto Espontâneo","Aborto Retido","Gravidez Molar","Doença Trofoblástica Gestacional",
  "Coriocarcinoma","Parto Prematuro","Ruptura Prematura de Membranas",
  "Oligoâmnio","Polidrâmnio","Restrição do Crescimento Intrauterino",
  "Morte Fetal","Hemorragia Pós-Parto","Atonia Uterina","Inversão Uterina",
  "Endometrite Pós-Parto","Mastite","Mastite Puerperal","Abscesso Mamário",
  "Síndrome dos Ovários Policísticos","Endometriose","Adenomiose",
  "Miomatose Uterina","Pólipo Endometrial","Hiperplasia Endometrial",
  "Vaginite Bacteriana","Candidíase Vaginal","Tricomoníase","Vaginose Bacteriana",
  "Doença Inflamatória Pélvica","Salpingite","Ooforite","Abscesso Tubo-Ovariano",
  "Torção de Ovário","Cisto Ovariano","Cisto Ovariano Roto","Torção de Pedículo",
  "Infertilidade Feminina","Insuficiência Ovariana Prematura","Menopausa",
  "Síndrome Climatérica","Osteoporose Pós-Menopausa",
  "Prolapso Uterino","Prolapso de Órgão Pélvico","Incontinência Urinária de Esforço",
  "Vulvodínia","Dispareunia","Vaginismo",

  // ── PSIQUIATRIA ───────────────────────────────────────────────
  "Depressão","Depressão Maior","Depressão Bipolar","Transtorno Depressivo Persistente",
  "Transtorno Bipolar Tipo I","Transtorno Bipolar Tipo II","Ciclotimia",
  "Esquizofrenia","Transtorno Esquizoafetivo","Transtorno Delirante","Psicose Breve",
  "Transtorno Obsessivo-Compulsivo","TOC","Transtorno de Ansiedade Generalizada",
  "Transtorno do Pânico","Fobia Social","Fobia Específica","Agorafobia",
  "Transtorno de Estresse Pós-Traumático","TEPT","Transtorno de Estresse Agudo",
  "Transtorno de Adaptação","Transtorno de Somatização","Transtorno Conversivo",
  "Hipocondria","Transtorno de Sintomas Somáticos",
  "Anorexia Nervosa","Bulimia Nervosa","Transtorno de Compulsão Alimentar",
  "Transtorno de Déficit de Atenção e Hiperatividade","TDAH",
  "Transtorno do Espectro Autista","Deficiência Intelectual",
  "Transtorno de Personalidade Borderline","Transtorno de Personalidade Antissocial",
  "Transtorno de Personalidade Narcisista","Transtorno de Personalidade Histriônica",
  "Dependência de Álcool","Síndrome de Abstinência Alcoólica","Delirium Tremens",
  "Dependência de Benzodiazepínico","Dependência de Opioide","Síndrome de Abstinência de Opioide",
  "Dependência de Cocaína","Dependência de Crack","Dependência de Cannabis",
  "Intoxicação por Substâncias","Síndrome Serotoninérgica","Síndrome Neuroléptica Maligna",
  "Síndrome de Burnout","Esgotamento Profissional","Luto Patológico",
  "Insônia Crônica","Hipersonia","Narcolepsia","Parassonias","Sonambulismo",
  "Ideação Suicida","Tentativa de Suicídio","Automutilação",
  "Delirium","Demência","Transtorno Neurocognitivo Maior","Transtorno Neurocognitivo Leve",

  // ── DERMATOLOGIA ──────────────────────────────────────────────
  "Psoríase","Psoríase em Placas","Psoríase Pustulosa","Psoríase Eritrodérmica",
  "Dermatite Atópica","Dermatite de Contato","Dermatite Seborreica",
  "Urticária","Angioedema","Urticária Crônica","Urticária Aguda",
  "Eritema Multiforme","Síndrome de Stevens-Johnson","Necrólise Epidérmica Tóxica",
  "Pênfigo Vulgar","Penfigoide Bolhoso","Dermatite Herpetiforme",
  "Acne Vulgar","Acne Rosácea","Rosácea","Perioral Dermatitis",
  "Celulite","Erisipela","Impetigo","Foliculite","Furúnculo","Carbúnculo",
  "Tinea Corporis","Tinea Pedis","Tinea Unguium","Tinea Capitis","Tinea Versicolor",
  "Candidíase Cutânea","Paroníquia","Onicomicose",
  "Herpes Simples","Herpes Zóster","Molusco Contagioso","Verruga Vulgar",
  "Condiloma Acuminado","Molluscum Contagiosum",
  "Vitiligo","Melasma","Hiperpigmentação Pós-Inflamatória","Albinismo",
  "Alopecia Androgenética","Alopecia Areata","Alopecia Cicatricial",
  "Escabiose","Pediculose","Larva Migrans","Miíase",
  "Carcinoma Basocelular","Carcinoma Espinocelular","Ceratose Actínica","Melanoma",
  "Nevo Displásico","Hemangioma","Queloide","Fibroma",
  "Eritema Nodoso","Vasculite Cutânea","Livedo Reticular","Fenômeno de Raynaud",
  "Esclerodermia Localizada","Morfeia","Líquen Plano","Líquen Escleroso",
  "Pitiríase Rósea","Pitiríase Versicolor","Eritema Migratório (Doença de Lyme)",

  // ── ORTOPEDIA / REUMATOLOGIA MUSCULOESQUELÉTICA ───────────────
  "Fratura de Quadril","Fratura de Fêmur","Fratura de Coluna","Fratura de Úmero",
  "Fratura de Rádio Distal","Fratura de Tornozelo","Fratura por Estresse",
  "Fratura Patológica","Luxação de Ombro","Luxação de Quadril","Luxação de Joelho",
  "Ruptura de Ligamento Cruzado Anterior","Ruptura de Menisco","Síndrome Femoropatelar",
  "Síndrome do Impacto do Ombro","Ruptura do Manguito Rotador","Tendinite",
  "Tendinite do Calcâneo","Tendinite Patelar","Síndrome de Iliotibial",
  "Epicondilite Lateral","Epicondilite Medial","Bursite","Bursite Subdeltóidea",
  "Bursite Trocantérica","Bursite Olecraniana","Bursite Pré-patelar",
  "Artrose de Joelho","Artrose de Quadril","Artrose de Coluna","Artrose de Mãos",
  "Espondiloartrose","Espondilose Cervical","Espondilose Lombar",
  "Lombalgia Inespecífica","Lombociatalgia","Ciática","Cervicalgia",
  "Síndrome de Lash","Síndrome do Piriforme","Síndrome de Piriformis",
  "Osteomielite Hematogênica","Osteomielite Crônica","Artrite Séptica",
  "Necrose Avascular","Necrose Avascular de Quadril","Doença de Legg-Calvé-Perthes",
  "Osteossarcoma","Condrossarcoma","Tumor de Células Gigantes","Encondroma",
  "Escoliose","Cifose","Lordose","Espondilolistese","Discopatia",
  "Síndrome do Túnel do Carpo","Síndrome do Canal de Guyon",
  "Dedo em Gatilho","Doença de Dupuytren","Doença de De Quervain",
  "Hallux Valgus","Fasciite Plantar","Esporão de Calcâneo",
  "Síndrome Compartimental","Síndrome de Esmagamento","Rabdomiólise",

  // ── UROLOGIA ──────────────────────────────────────────────────
  "Hiperplasia Prostática Benigna","Câncer de Próstata","Prostatite Aguda",
  "Prostatite Crônica","Abscesso Prostático","Prostatite Bacteriana",
  "Câncer de Rim","Câncer de Bexiga","Câncer Testicular","Tumor de Wilms",
  "Orquite","Epididimite","Orquiepididimite","Torção Testicular",
  "Varicocele","Hidrocele","Espermatocele","Fimose","Parafimose",
  "Priapismo","Disfunção Erétil","Ejaculação Precoce","Hipogonadismo",
  "Urolitíase","Nefrolitíase","Cálculo Ureteral","Cálculo Vesical",
  "Incontinência Urinária","Bexiga Hiperativa","Retenção Urinária Aguda",
  "Estenose Uretral","Extrofia Vesical","Hipospádia","Epispádia",

  // ── OFTALMOLOGIA ──────────────────────────────────────────────
  "Glaucoma","Glaucoma Agudo de Ângulo Fechado","Glaucoma Crônico de Ângulo Aberto",
  "Catarata","Descolamento de Retina","Oclusão de Artéria Central da Retina",
  "Oclusão de Veia Central da Retina","Retinopatia Diabética","Degeneração Macular",
  "Degeneração Macular Relacionada à Idade","Neuropatia Óptica Isquêmica",
  "Neurite Óptica","Papilite","Papiledema","Celulite Orbitária","Celulite Pré-septal",
  "Uveíte","Uveíte Anterior","Uveíte Posterior","Pan-uveíte",
  "Conjuntivite Bacteriana","Conjuntivite Viral","Conjuntivite Alérgica",
  "Queratite","Úlcera de Córnea","Ceratocone","Hordéolo","Calázio","Dacriocistite",
  "Estrabismo","Ambliopia","Miastenia Gravis Ocular",

  // ── OTORRINOLARINGOLOGIA ──────────────────────────────────────
  "Otite Média Aguda","Otite Média Crônica","Otite Média com Efusão",
  "Otite Externa","Mastoidite","Colesteatoma","Perfuração Timpânica",
  "Surdez Súbita","Perda Auditiva Neurossensorial","Presbiacusia",
  "Síndrome de Ménière","Vertigem Posicional Paroxística Benigna",
  "Neurite Vestibular","Labirintite","Zumbido",
  "Sinusite Aguda","Sinusite Crônica","Rinossinusite","Polipose Nasal",
  "Rinite Alérgica","Rinite Vasomotora","Epistaxe",
  "Amigdalite Aguda","Amigdalite Crônica","Abscesso Peritonsilar",
  "Adenoidite","Laringite","Laringite Epiglótica","Epiglotite","Crupe Viral",
  "Paralisia de Pregas Vocais","Nódulo de Corda Vocal","Pólipo de Corda Vocal",
  "Câncer de Laringe","Câncer de Faringe","Câncer de Nasofaringe",

  // ── PEDIATRIA ─────────────────────────────────────────────────
  "Bronquiolite Viral","Bronquiolite por VSR","Laringite Viral","Crupe",
  "Pneumonia em Crianças","Otite Média Aguda em Crianças","Febre sem Foco",
  "Doença de Kawasaki","Síndrome de Reye","Doença de Hirschsprung",
  "Enterocolite Necrosante","Atresia de Esôfago","Atresia de Duodeno",
  "Estenose Hipertrófica do Piloro","Invaginação Intestinal","Volvo Neonatal",
  "Anemia Hemolítica Neonatal","Icterícia Neonatal","Sepse Neonatal",
  "Meningite Neonatal","Síndrome do Desconforto Respiratório Neonatal",
  "Displasia Broncopulmonar","Apneia do Prematuro","Síndrome da Morte Súbita do Lactente",
  "Doença Celíaca em Crianças","Síndrome de Beckwith-Wiedemann",
  "Diabetes Mellitus Tipo 1 em Crianças","Fibrose Cística em Crianças",
  "Síndrome de Down","Síndrome de Turner","Síndrome de Klinefelter",
  "Fenilcetonúria","Hipotireoidismo Congênito","Galactosemia",
  "Talassemia em Crianças","Anemia Falciforme em Crianças",
  "Tumor de Wilms","Neuroblastoma","Retinoblastoma","Leucemia Aguda em Crianças",
  "Meningite Bacteriana em Crianças","Sepse em Crianças",
  "Coqueluche","Sarampo","Caxumba","Varicela em Crianças","Rubéola",
  "Escarlatina","Impetigo em Crianças","Síndrome de Mão Pé Boca",
  "Gastroenterite Viral","Diarreia Aguda em Crianças","Desidratação em Crianças",
  "Desnutrição","Kwashiorkor","Marasmo",
  "Doenças do Refluxo em Lactentes","Constipação em Crianças",
  "Asma em Crianças","Rinite Alérgica em Crianças","Dermatite Atópica em Crianças",

  // ── EMERGÊNCIA / UTI ──────────────────────────────────────────
  "Sepse","Sepse Grave","Choque Séptico","Choque Hipovolêmico","Choque Hemorrágico",
  "Choque Cardiogênico","Choque Distributivo","Choque Anafilático","Anafilaxia",
  "Parada Cardiorrespiratória","Ressuscitação Cardiopulmonar",
  "Politrauma","Traumatismo Cranioencefálico","TCE Leve","TCE Grave",
  "Traumatismo Raquimedular","Lesão Medular","Pneumotórax Traumático",
  "Hemotórax","Tamponamento Cardíaco Traumático","Contusão Pulmonar",
  "Contusão Miocárdica","Rotura de Diafragma","Trauma Abdominal",
  "Trauma Esplênico","Laceração Hepática","Trauma Renal","Ruptura de Bexiga",
  "Queimadura","Queimadura Grave","Síndrome de Inalação",
  "Afogamento","Hipotermia","Hipertermia","Golpe de Calor",
  "Intoxicação por Organofosforado","Intoxicação por Carbono",
  "Intoxicação por Paracetamol","Intoxicação por Benzodiazepínico",
  "Intoxicação por Antidepressivo Tricíclico","Intoxicação por Opioide",
  "Intoxicação por Álcool Metílico","Intoxicação por Etilenoglicol",
  "Rabdomiólise Traumática","Síndrome do Esmagamento",
  "Embolia Gasosa","Embolia Gordurosa","Embolia por Líquido Amniótico",
  "Síndrome Compartimental Abdominal","Hipertensão Intra-abdominal",
  "Síndrome de Disfunção de Múltiplos Órgãos","SDMO",

  // ── MEDICINA DO TRABALHO / MEDICINA DE FAMÍLIA ────────────────
  "Lombalgia Ocupacional","LER / DORT","Síndrome do Impacto","Tendinite Ocupacional",
  "Surdez Ocupacional","Pneumoconiose","Silicose","Asbestose","Bissinose",
  "Dermatite Ocupacional","Intoxicação por Metais Pesados","Saturnismo",
  "Hipertensão Arterial","Síndrome Metabólica","Obesidade",
  "Tabagismo","Alcoolismo","Dependência de Nicotina",

  // ── DOENÇAS RARAS / MISCELÂNEA ────────────────────────────────
  "Síndrome de Marfan","Síndrome de Ehlers-Danlos","Osteogênese Imperfeita",
  "Neurofibromatose","Esclerose Tuberosa","Síndrome de Von Hippel-Lindau",
  "Síndrome de Li-Fraumeni","Síndrome de Lynch","Doença de Wilson","Hemocromatose",
  "Doença de Gaucher","Doença de Niemann-Pick","Doença de Fabry",
  "Mucopolissacaridose","Glicogenose","Porfiria","Amiloidose Sistêmica",
  "Síndrome de Good","Imunodeficiência Comum Variável","Agamaglobulinemia de Bruton",
  "Síndrome de DiGeorge","Síndrome de Wiskott-Aldrich","Ataxia-Telangiectasia",
  "Síndrome de Chediak-Higashi","Doença Granulomatosa Crônica",
  "Síndrome POEMS","Síndrome de Sweet","Síndrome de Still do Adulto",
  "Doença de Kikuchi-Fujimoto","Doença de Rosai-Dorfman",
  "Síndrome de Hamman-Rich","Síndrome de Goodpasture","Síndrome de Alport",
  "Doença de Erdheim-Chester","Doença de Castleman",
  "Síndrome de Fanconi","Síndrome de Bloom","Anemia Diamond-Blackfan",
  "Doença de Hirschsprung","Síndrome de Alagille","Síndrome de Crigler-Najjar",
  "Síndrome de Gilbert","Síndrome de Dubin-Johnson","Síndrome de Rotor",
  "Doença de Whipple","Doença de Ménétrier","Gastroenteropatia Perdedora de Proteína",
  "Síndrome de Ogilvie","Síndrome de Zollinger-Ellison","Síndrome de Verner-Morrison",
  "Síndrome Carcinoide","Mastocitose","Histiocitose de Células de Langerhans",
  "Síndrome de Löfgren","Neurossarcoidose","Sarcoidose Cardíaca"
];
